server:
  port: 9000
  servlet:
    contextPath: /dev

spring:
  jpa:
    database: HSQL
    properties:
      hibernate:
        format_sql: true
        show_sql: true

security:
  oauth2:
    clientId: acme
    clientSecret: acmesecret
    accessTokenUri: /oauth/token
    userAuthorizationUri: /oauth/authorize
    resource:
      userInfoUri: /user
      preferTokenInfo: false
      jwt:
        keyValue: |
          -----BEGIN NEW CERTIFICATE REQUEST-----
          MIIC2DCCAcACAQAwYzELMAkGA1UEBhMCQlIxCzAJBgNVBAgTAlBFMQ8wDQYDVQQHEwZSZWNpZmUxDDAKBgNVBAoTA0pESDEMMAoGA1UECxMDSkRIMRowGAYDVQQDExFEYW5pZWwgSGVyc3plbm9ybjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIfMJPq65Qa/uMSXpw6qJD5chW1+L794DGdPyQzQ9P/XtzqT7gHEFsiuk5rP6tojxHVyMnZsNLiP3NZg9r4VM6YhBYBFj4ndGqiodj3s4Om6p2abw8NoAoCkKjE2mFqzhGwKaSh92iAdS3d3+uMUcZbyikW51fW6Vxi5YP57NhPoD81n6Vp+GjpmJ1VOOUJ9TTA3VIEr/4M/DsCvUyQxLTdn5YokW+l/NQeKfEELoDUTzXQtCji2Qi1Qtl0kepBFeFLpopXDlvd+UwmtnYnzwmjqgGGM5as44T1EVrsgPNU2p6Uw1dAO015tCuZzcJoyEUyYDchTjE5BeIH7dw9YvRkCAwEAAaAwMC4GCSqGSIb3DQEJDjEhMB8wHQYDVR0OBBYEFEI03J9lPi+2V54v00hjkJcQJ5R7MA0GCSqGSIb3DQEBCwUAA4IBAQBLLyI7kQlv0OklSzBL8ls/w2jPy57F7DlogyQQVLyKjveXJXnBtG99gXUkR/wz41lfnh0HGqFRZDodIePb3cAqSGI1Ecv/0e5frV2Bb3sD7ggHgFGzzAGSCn1DgLvyASfTgmhZeKVW970AfbDmVsHJH5XDJk1FInHbTLntKSQG4Tw2D+GHBZkhMp5HxKtJXXnYAyacOuMiqh+GG3H/Jn8KiANGyTebRJP41H6uATQRZcVFWAGR88jFOJlDD0X2GpEF6s9MEjU9yZCaqftFtwm0SjfDS0LRYaDYC4GOGaztFVIZ9161URGSbAcE+GpMZKYok15eMlmh/4qHlaeGqaZ3
          -----END NEW CERTIFICATE REQUEST-----
#logging:
#  level:
#    org.springframework.security: DEBUG